# Generated by Django 4.2.7 on 2023-11-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_messages_message_alter_room_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='host',
            new_name='user',
        ),
    ]
